name: pr

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  pr-tests:
    name: Build and test images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [webhook, api, operator]
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find current tag version
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: tags

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: run tests
        run: make test

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.5.0
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: ${{ github.REPOSITORY_OWNER }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.REPOSITORY_OWNER }}/kubi-${{ matrix.component }}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push development image into ghcr (packages)
        run: |
          docker push ${{ steps.meta.outputs.image }}